#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct  4 13:09:31 2018

@author: allisonetipton
"""
import numpy as np
import math
import matplotlib.pyplot as plt 

def alphaM(V):
    return (2.5-0.1*(V+65)) / (np.exp(2.5-0.1*(V+65)) -1)

def betaM(V):
    return 4*np.exp(-(V+65)/18)

def alphaH(V):
    return 0.07*np.exp(-(V+65)/20)

def betaH(V):
    return 1/(np.exp(3.0-0.1*(V+65))+1)

def alphaN(V):
    return (0.1-0.01*(V+65)) / (np.exp(1-0.1*(V+65)) -1)

def betaN(V):
    return 0.125*np.exp(-(V+65)/80)

def HH(I0,T0):
    dt = 0.01;
    T  = math.ceil(T0/dt)  # [ms]
    gNa0 = 120   # [mS/cm^2]
    ENa  = 115;  # [mV]
    gK0  = 36;   # [mS/cm^2]
    EK   = -12;  # [mV]
    gL0  = 0.3;  # [mS/cm^2]
    EL   = 10.6; # [mV]

    t = np.arange(0,T)*dt
    V = np.zeros([T,1])
    m = np.zeros([T,1])
    h = np.zeros([T,1])
    n = np.zeros([T,1])

    V[0]=-70.0
    m[0]=0.05
    h[0]=0.54
    n[0]=0.34

    for i in range(0,T-1):
        V[i+1] = V[i] + dt*(gNa0*m[i]**3*h[i]*(ENa-(V[i]+65)) + gK0*n[i]**4*(EK-(V[i]+65)) + gL0*(EL-(V[i]+65)) + I0);
        m[i+1] = m[i] + dt*(alphaM(V[i])*(1-m[i]) - betaM(V[i])*m[i]);
        h[i+1] = h[i] + dt*(alphaH(V[i])*(1-h[i]) - betaH(V[i])*h[i]);
        n[i+1] = n[i] + dt*(alphaN(V[i])*(1-n[i]) - betaN(V[i])*n[i]);
    return V,m,h,n,t



I0 = 7
T0 = 100
[V,m,h,n,t]=HH(I0,T0) 


plt.figure()
ax1 = plt.subplot(211);                 # Define axis for 1st subplot,
ax2 = plt.subplot(212, sharex=ax1);     # ... and link axis of 2nd subplot to the 1st.
ax1.plot(t,V,'k')                       # Plot the voltage in the first subplot,
plt.xlim([42, 56]);
ax2.plot(t,m,'r', label='m')            # ... and the gating variables in the other subplot.
ax2.plot(t,h,'b', label='h')
ax2.plot(t,n,'g', label='n');
plt.xlabel('Time [ms]');
plt.legend();

                             #Firing rate curve calculation and plot
import numpy as np
import matplotlib.pyplot as plt 
from scipy.signal import find_peaks 

MinInput = 0 #Minimum input current to evaluate
MaxInput = 50 #Maximum input current to evaluate
T = 500 #Time to run the model, in ms
FI = np.zeros([MaxInput,1]) #Create empty vector to store results

for i in range(MinInput, MaxInput):
    [V,m,h,n,t] = HH(i,T) #Run the model for input current i 
    peaks, _  = find_peaks(np.reshape(V, -1), height=-20) #Find peaks using someone else's function, -20 is threshold for definition of a peak
    FI[i] = np.shape(peaks) #Number of peaks in 200-ms
    
Current = np.linspace(MinInput, MaxInput, num=MaxInput)
plt.plot(Current, FI, 'k')
plt.xlabel('Input current (uA/cm2)')                   
plt.ylabel('Firing rate (Hz)')             
plt.title('F-I Curve for Hodgkin Huxley Model')   
